version: "2"

services:
  i2c_display:
    build: .
    restart: always
    # devices:
    #   - "/dev/i2c-1:/dev/i2c-1"
    #   - "/dev/mem:/dev/mem"
    # cap_add:
      # - SYS_RAWIO
    # labels:
    #   io.balena.features.kernel-modules: '1'

    # privileged: true
